### ISSUE TITLE
Traceback when adding a program to the local vm without an internet connection

### ISSUE THREAD

**Issue by eax64** [vigilate/backend#126]
If the backend can't access `static.nvd.nist.gov` (no internet or host down) and a program is added, the backend will traceback with this message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.5/dist-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/viewsets.py", line 87, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 466, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.5/dist-packages/rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "./vigilate_backend/views.py", line 165, in create
    (cpe, up_to_date) =  cpe_updater.get_cpe_from_name_version(elem['program_name'], elem['program_version'], up_to_date)
  File "./vulnerability_manager/cpe_updater.py", line 27, in get_cpe_from_name_version
    do_update()
  File "./vulnerability_manager/cpe_updater.py", line 8, in do_update
    r = requests.get(xml_url)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 423, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='static.nvd.nist.gov', port=80): Max retries exceeded with url: /feeds/xml/cpe/dictionary/official-cpe-dictionary_v2.3.xml (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7feb2c0e1cc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
```

**Comment by ampotos** [comment]
maybe a simple try/except can be enough to fix that
